--- drivers/gpu/arm/t7xx/r5p0/Kbuild
+++ drivers/gpu/arm/t7xx/r5p0/Kbuild
@@ -15,7 +15,7 @@
 
 
 # Driver version string which is returned to userspace via an ioctl
-MALI_RELEASE_NAME ?= "r5p0-06rel0"
+MALI_RELEASE_NAME ?= "r5p1-00rel1"
 
 # Paths required for build
 KBASE_PATH = $(src)
